---
- name: Include vars
  include_vars:
    dir: vars

- name: Create apache directories
  file:
    name: "{{item}}"
    state: directory
  with_items:
    - "{{document_root}}/{{projekts.projekt1.name}}"
    - "{{document_root}}/{{projekts.projekt2.name}}"

- name: Deploy default wordpress setup
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "{{item}}"
    remote_src: True
  with_items:
    - "{{document_root}}/{{projekts.projekt1.name}}"
    - "{{document_root}}/{{projekts.projekt2.name}}"

- name: Deploy apache configuration
  template:
    src: "projekt.j2"
    dest: "{{apache_conf_path}}/{{projekts[*]name}}"
  with_items:
    - "{{projekts[*]name}}"

- name: Activate apache site
  command: "a2ensite {{projekts.projekt1.name}} {{projekts.projekt2.name}}"

- name: Reload apache
  service:
    name: apache2
    state: reloaded

- include: mysql.yml
  tags: mysql
