---
- name: Install the Python MySQLB module
  pip: 
    name: MySQL-python

- name: Create MySQL user
  mysql_user:
    name: eligere
    host: localhost
    state: present

# Not working yet
- name: Create MySQL db
  mysql_db: 
    name: "{{projekt}}"
    login_user: "root"
    config_file: "/etc/mysql/my.cnf" 
