---
- name: Install apt updates
  apt:
    upgrade: dist

- name: Install default apt packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - apache2
    - htop
    - mysql-server
    - ansible
    - git

- name: Create default groups
  group:
    name: "{{item}}"
    state: present
  with_items:
    - admins
    - developer

- name: Create default users
  user:
    name: "{{item.value.name}}"
    group: "{{item.value.group}}"
  with_dict: "{{users}}"

- name: Insert default lines into .bashrc files
  lineinfile:
    line: "alias ll='ls -lh'"
    dest: "{{item.value.home}}/.bashrc"
    state: present
  with_dict: "{{users}}"

- name: Create ssh directory for developer
  file:
    name: "{{developer_home}}/.ssh"
    owner: "developer"
    group: "developer"
    state: directory

- name: Deploy ssh-key so checkout is possible
  copy:
    src: "../files/id_rsa"
    dest: "{{developer_home}}/.ssh/id_rsa"
    owner: "developer"
    group: "developer"
    mode: 0600

- include: apache.yml
  tags: apache
